"""add user config order by frequency

Revision ID: 32b1d801d740
Revises: 3e74790c0d3c
Create Date: 2020-03-24 23:10:28.286811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b1d801d740'
down_revision = '3e74790c0d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userconfig', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userconfig', 'order')
    # ### end Alembic commands ###
